import QtQuick 2.4
import QtQuick.Controls 1.2

Rectangle{
    id:full_keyboard
    width:770
    height:280
    color:"transparent"
    signal letter_button_clicked(string str)
    signal function_button_clicked(string str)




    LetterButton{
        x:0
        y:0
        show_text:"1"
    }
    LetterButton{
        x:70
        y:0
        show_text:"2"
    }
    LetterButton{
        x:140
        y:0
        show_text:"3"
    }
    LetterButton{
        x:210
        y:0
        show_text:"4"
    }
    LetterButton{
        x:280
        y:0
        show_text:"5"
    }
    LetterButton{
        x:350
        y:0
        show_text:"6"
    }
    LetterButton{
        x:420
        y:0
        show_text:"7"
    }
    LetterButton{
        x:490
        y:0
        show_text:"8"
    }
    LetterButton{
        x:560
        y:0
        show_text:"9"
    }
    LetterButton{
        x:630
        y:0
        show_text:"0"
    }
    LetterButton{
        x:700
        y:0
        show_text:"-"
    }
    LetterButton{
        x:35
        y:70
        show_text:"Q"
    }
    LetterButton{
        x:105
        y:70
        show_text:"W"
    }
    LetterButton{
        x:175
        y:70
        show_text:"E"
    }
    LetterButton{
        x:245
        y:70
        show_text:"R"
    }
    LetterButton{
        x:315
        y:70
        show_text:"T"
    }
    LetterButton{
        x:385
        y:70
        show_text:"Y"
    }
    LetterButton{
        x:455
        y:70
        show_text:"U"
    }
    LetterButton{
        x:525
        y:70
        show_text:"I"
    }
    LetterButton{
        x:595
        y:70
        show_text:"O"
    }
    LetterButton{
        x:665
        y:70
        show_text:"P"
    }
    LetterButton{
        x:70
        y:140
        show_text:"A"
    }
    LetterButton{
        x:140
        y:140
        show_text:"S"
    }
    LetterButton{
        x:210
        y:140
        show_text:"D"
    }
    LetterButton{
        x:280
        y:140
        show_text:"F"
    }
    LetterButton{
        x:350
        y:140
        show_text:"G"
    }
    LetterButton{
        x:420
        y:140
        show_text:"H"
    }
    LetterButton{
        x:490
        y:140
        show_text:"J"
    }
    LetterButton{
        x:560
        y:140
        show_text:"K"
    }
    LetterButton{
        x:630
        y:140
        show_text:"L"
    }
    LetterButton{
        x:105
        y:210
        show_text:"Z"
    }
    LetterButton{
        x:175
        y:210
        show_text:"X"
    }
    LetterButton{
        x:245
        y:210
        show_text:"C"
    }
    LetterButton{
        x:315
        y:210
        show_text:"V"
    }
    LetterButton{
        x:385
        y:210
        show_text:"B"
    }
    LetterButton{
        x:455
        y:210
        show_text:"N"
    }
    LetterButton{
        x:525
        y:210
        show_text:"M"
    }
    BackspaceButton{
        x:35
        y:210
    }

    KeyboardFunctionButton{
        x:665
        y:210
        slot_text:"ok"
        show_image:"img/button/OkButton.png"
    }

    KeyboardFunctionButton{
        x:595
        y:210
        slot_text:"delete"    //退格删除键
        show_image:"img/button/DeleteButton.png"
    }
}
